### PR TITLE
-- added peace

### PR DESCRIPTION
**Pull request by bissat**
adding peace to the Mind

### CODE REVIEW

**Comment by bissat** [comment]
-- peace is not important when you are in constant motion. so , just keep moving. now please remove the peace.

**Review by mnsgit96 — COMMENTED** [review]
can you just add one more line by saying "God, make me an instrument of your peace"

**Comment by bissat** [comment]
Hi mnsgit, I have added the change according to your suggestion. Please review.

**Review by mnsgit96 — APPROVED** [review]
approved

**Pull request merged**
